# 18BCE101

## DM prac 7

### Part 1-   Let, x <- c(5,2,1,4) and y <- rep(1,5) then find  the output of the followings in R

In [2]:
x <- c(5,2,1,4) 
y <- rep(1,5) 

In [3]:
sum(x)

[1] 12

In [4]:
range(x)

[1] 1 5

In [5]:
length(y)

[1] 5

In [6]:
sum(y)

[1] 5

In [9]:
#concat of x and y in 1D array

c(x,y,13)

[1]  5  2  1  4  1  1  1  1  1 13

In [8]:
y

[1] 1 1 1 1 1

In [14]:
x[4]

[1] 4

In [15]:
#product of 4th index in x and 2nd index in y (indexing from 1)

x[4] * y[2]

[1] 4

In [17]:
#[2 1 4] * [5 1 2]

x[2:4] * x[1:3]

[1] 10  2  4

In [19]:
(x <= 2)

[1] FALSE  TRUE  TRUE FALSE

In [20]:
(x[x <=2])

[1] 2 1

In [21]:
rep(1:4,2)

[1] 1 2 3 4 1 2 3 4

In [22]:
rep(1:4,each = 2)

[1] 1 1 2 2 3 3 4 4

In [24]:
rep(1:4,c(2,2,3,2))

[1] 1 1 2 2 3 3 3 4 4

In [25]:
rep(1:4,c(2,1,2,1))

[1] 1 1 2 3 3 4

In [26]:
rep(1:4,each = 2,len = 10)

[1] 1 1 2 2 3 3 4 4 1 1

In [27]:
2:3^2

[1] 2 3 4 5 6 7 8 9

In [31]:
seq(4,-3) * c(-1,1)

[1] -4  3 -2  1  0 -1  2 -3

### Part 2.	Let a <- LETTERS[1:3], evaluate

In [33]:
a <- LETTERS[1:3]
a

[1] "A" "B" "C"

In [37]:
paste('V',a,sep = ":")

[1] "V:A" "V:B" "V:C"

In [38]:
nchar(paste(a, collapse = '<'))

[1] 5

### Part 3.Let u <- c(TRUE,FALSE,TRUE,TRUE), evaluate

In [39]:
u <- c(TRUE,FALSE,TRUE,TRUE)

In [40]:
u

[1]  TRUE FALSE  TRUE  TRUE

In [41]:
!u

[1] FALSE  TRUE FALSE FALSE

In [42]:
u | !u

[1] TRUE TRUE TRUE TRUE

In [43]:
#Given a set of logical vectors, is at least one of the values true?

any(u)

[1] TRUE

### Part 4	Generate following vectors

In [ ]:
10:0

In [4]:
data <- 1:10
newdata <- data^2
rep(newdata, each = 4)

[1]   1   1   1   1   4   4   4   4   9   9   9   9  16  16  16  16  25  25  25
[20]  25  36  36  36  36  49  49  49  49  64  64  64  64  81  81  81  81 100 100
[39] 100 100

In [11]:
a <- 1:16
paste(letters[1:16],a,sep = ":")

[1] "a:1"  "b:2"  "c:3"  "d:4"  "e:5"  "f:6"  "g:7"  "h:8"  "i:9"  "j:10"
[11] "k:11" "l:12" "m:13" "n:14" "o:15" "p:16"

### Part 5

In [17]:
m1 <- matrix(5.5:15, 2, 10)
print(m1)

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  5.5  7.5  9.5 11.5 13.5  5.5  7.5  9.5 11.5  13.5
[2,]  6.5  8.5 10.5 12.5 14.5  6.5  8.5 10.5 12.5  14.5


In [22]:
m2 <- t(m1)
print(m2)

      [,1] [,2]
 [1,]  5.5  6.5
 [2,]  7.5  8.5
 [3,]  9.5 10.5
 [4,] 11.5 12.5
 [5,] 13.5 14.5
 [6,]  5.5  6.5
 [7,]  7.5  8.5
 [8,]  9.5 10.5
 [9,] 11.5 12.5
[10,] 13.5 14.5


In [23]:
print(m1 %*% m2)

       [,1]   [,2]
[1,]  982.5 1077.5
[2,] 1077.5 1182.5


## Conclusion

R is a free software environment for statistical computing and graphics. R and Python are both open-source programming languages with a large community.

The r is primarily used for statistical analysis while Python provides a more general approach to data science. 
Python is more popular in general but for statistical jobs r is preferred